# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommunicator.proto\x12\x0c\x63ommunicator\"\x9d\x01\n\x10ObservationProto\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x13\n\x0bgame_states\x18\x04 \x01(\t\x12\x1a\n\x12\x66loat_observations\x18\x05 \x03(\x02\x12\x18\n\x10int_observations\x18\x06 \x03(\x05\x12\x13\n\x0b\x61pi_returns\x18\x07 \x01(\t\"~\n\x0b\x41\x63tionProto\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x14\n\x0cjson_actions\x18\x03 \x01(\t\x12\x15\n\rfloat_actions\x18\x04 \x03(\x02\x12\x13\n\x0bint_actions\x18\x05 \x03(\x05\x12\x11\n\tapi_calls\x18\x06 \x01(\t2X\n\x0c\x43ommunicator\x12H\n\tGetAction\x12\x1e.communicator.ObservationProto\x1a\x19.communicator.ActionProto\"\x00\x62\x06proto3')



_OBSERVATIONPROTO = DESCRIPTOR.message_types_by_name['ObservationProto']
_ACTIONPROTO = DESCRIPTOR.message_types_by_name['ActionProto']
ObservationProto = _reflection.GeneratedProtocolMessageType('ObservationProto', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONPROTO,
  '__module__' : 'legent.protobuf.communicator_pb2'
  # @@protoc_insertion_point(class_scope:communicator.ObservationProto)
  })
_sym_db.RegisterMessage(ObservationProto)

ActionProto = _reflection.GeneratedProtocolMessageType('ActionProto', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONPROTO,
  '__module__' : 'legent.protobuf.communicator_pb2'
  # @@protoc_insertion_point(class_scope:communicator.ActionProto)
  })
_sym_db.RegisterMessage(ActionProto)

_COMMUNICATOR = DESCRIPTOR.services_by_name['Communicator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVATIONPROTO._serialized_start=37
  _OBSERVATIONPROTO._serialized_end=194
  _ACTIONPROTO._serialized_start=196
  _ACTIONPROTO._serialized_end=322
  _COMMUNICATOR._serialized_start=324
  _COMMUNICATOR._serialized_end=412
# @@protoc_insertion_point(module_scope)
